language: php
php:
    - '5.6'
before_script:
    - composer install
    - composer dump-autoload -o
script:
    - vendor/bin/phpunit
services:
    - mysql
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
